services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_PASSWORD=changeMe123!
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Projectly_prod
      POSTGRES_USER: Projectly_user
      POSTGRES_PASSWORD: "changeMe123!"
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

