global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    application: 'Projectly'
    environment: 'production'

scrape_configs:
  - job_name: 'projectly-actuator'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
