
-- V1__Init_Security_Tables.sql

-- Create roles table
CREATE TABLE IF NOT EXISTS roles (
    id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::text,
    ref VARCHAR(500) UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_roles_name ON roles(name);

-- Hibernate Envers revision tracking
CREATE TABLE IF NOT EXISTS revinfo (
    rev     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

-- Create users table with dynamic fields based on configuration
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::text,
    ref VARCHAR(500) UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_enabled BOOLEAN DEFAULT TRUE,
    is_locked BOOLEAN DEFAULT FALSE,
    is_credentials_expired BOOLEAN DEFAULT FALSE,
    is_email_verified BOOLEAN DEFAULT FALSE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Create users_roles join table
CREATE TABLE IF NOT EXISTS users_roles (
    users_id VARCHAR(255) NOT NULL,
    roles_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (users_id, roles_id),
    FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (roles_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_users_roles_role_id ON users_roles(roles_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_active ON users(email) WHERE deleted_at IS NULL;

-- Create application entity tables (PostgreSQL, excluding User)
CREATE TABLE IF NOT EXISTS app_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    owner_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_project_ref ON app_project(ref);
CREATE INDEX IF NOT EXISTS idx_app_project_owner_id ON app_project(owner_id);

CREATE TABLE IF NOT EXISTS app_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    priority VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL,
    due_date DATE,
    internal_note VARCHAR(255),
    project_id BIGINT NOT NULL,
    assignee_id VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_task_ref ON app_task(ref);
CREATE INDEX IF NOT EXISTS idx_app_task_project_id ON app_task(project_id);
CREATE INDEX IF NOT EXISTS idx_app_task_assignee_id ON app_task(assignee_id);

CREATE TABLE IF NOT EXISTS app_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    body VARCHAR(255) NOT NULL,
    task_id BIGINT NOT NULL,
    author_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_comment_ref ON app_comment(ref);
CREATE INDEX IF NOT EXISTS idx_app_comment_task_id ON app_comment(task_id);
CREATE INDEX IF NOT EXISTS idx_app_comment_author_id ON app_comment(author_id);


-- Create join tables for ManyToMany relationships (PostgreSQL)

-- Insert initial roles from configuration
INSERT INTO roles (id, name, created_date, created_by) 
SELECT gen_random_uuid()::text, 'ROLE_ADMIN', NOW(), 'system'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_ADMIN');

INSERT INTO roles (id, name, created_date, created_by) 
SELECT gen_random_uuid()::text, 'ROLE_MANAGER', NOW(), 'system'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_MANAGER');

INSERT INTO roles (id, name, created_date, created_by) 
SELECT gen_random_uuid()::text, 'ROLE_MEMBER', NOW(), 'system'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_MEMBER');


